# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import musicService_pb2 as musicService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in musicService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.filterAllSongs = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllSongs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.getSongById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getSongById',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.filterSongsByTitle = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterSongsByTitle',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.filterSongsByArtistId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterSongsByArtistId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.filterSongsBySongType = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterSongsBySongType',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.createSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createSong',
                request_serializer=musicService__pb2.CreateSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.updateSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/updateSong',
                request_serializer=musicService__pb2.UpdateSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.deleteSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteSong',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.filterAllAlbums = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllAlbums',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.getAlbumById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getAlbumById',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.filterAlbumsByName = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAlbumsByName',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.filterAlbumsByArtistId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAlbumsByArtistId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.createAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createAlbum',
                request_serializer=musicService__pb2.CreateAlbumRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.updateAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/updateAlbum',
                request_serializer=musicService__pb2.UpdateAlbumRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.deleteAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteAlbum',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.filterAllGenres = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllGenres',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.getGenreById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getGenreById',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.filterGenresByName = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterGenresByName',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.createGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createGenre',
                request_serializer=musicService__pb2.CreateGenreRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.updateGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/updateGenre',
                request_serializer=musicService__pb2.UpdateGenreRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.deleteGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteGenre',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.filterAllAlbumSongs = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllAlbumSongs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.getAlbumSongByIds = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getAlbumSongByIds',
                request_serializer=musicService__pb2.CreateAlbumSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.filterAlbumSongsByAlbumId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAlbumSongsByAlbumId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.filterAlbumSongsBySongId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAlbumSongsBySongId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.createAlbumSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createAlbumSong',
                request_serializer=musicService__pb2.CreateAlbumSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.deleteAlbumSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteAlbumSong',
                request_serializer=musicService__pb2.CreateAlbumSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.filterAllGenreSongs = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllGenreSongs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.getGenreSongByIds = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getGenreSongByIds',
                request_serializer=musicService__pb2.CreateGenreSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.filterGenreSongsByGenreId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterGenreSongsByGenreId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.filterGenreSongsBySongId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterGenreSongsBySongId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.createGenreSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createGenreSong',
                request_serializer=musicService__pb2.CreateGenreSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.deleteGenreSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteGenreSong',
                request_serializer=musicService__pb2.CreateGenreSongRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreSong.FromString,
                _registered_method=True)
        self.filterAllSongSubArtists = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterAllSongSubArtists',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)
        self.getSongSubArtistByIds = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/getSongSubArtistByIds',
                request_serializer=musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)
        self.filterSongSubArtistsBySongId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterSongSubArtistsBySongId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)
        self.filterSongSubArtistsBySubArtistId = channel.unary_stream(
                '/app.grpc.protos.music.MusicService/filterSongSubArtistsBySubArtistId',
                request_serializer=musicService__pb2.StringRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)
        self.createSongSubArtist = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/createSongSubArtist',
                request_serializer=musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)
        self.deleteSongSubArtist = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/deleteSongSubArtist',
                request_serializer=musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongSubArtist.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def filterAllSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSongById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterSongsByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterSongsByArtistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterSongsBySongType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAllAlbums(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAlbumById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAlbumsByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAlbumsByArtistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAllGenres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGenreById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterGenresByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAllAlbumSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAlbumSongByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAlbumSongsByAlbumId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAlbumSongsBySongId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAlbumSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteAlbumSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAllGenreSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGenreSongByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterGenreSongsByGenreId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterGenreSongsBySongId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createGenreSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteGenreSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterAllSongSubArtists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSongSubArtistByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterSongSubArtistsBySongId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def filterSongSubArtistsBySubArtistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createSongSubArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteSongSubArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'filterAllSongs': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllSongs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'getSongById': grpc.unary_unary_rpc_method_handler(
                    servicer.getSongById,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'filterSongsByTitle': grpc.unary_stream_rpc_method_handler(
                    servicer.filterSongsByTitle,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'filterSongsByArtistId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterSongsByArtistId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'filterSongsBySongType': grpc.unary_stream_rpc_method_handler(
                    servicer.filterSongsBySongType,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'createSong': grpc.unary_unary_rpc_method_handler(
                    servicer.createSong,
                    request_deserializer=musicService__pb2.CreateSongRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'updateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.updateSong,
                    request_deserializer=musicService__pb2.UpdateSongRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'deleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteSong,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'filterAllAlbums': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllAlbums,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'getAlbumById': grpc.unary_unary_rpc_method_handler(
                    servicer.getAlbumById,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'filterAlbumsByName': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAlbumsByName,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'filterAlbumsByArtistId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAlbumsByArtistId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'createAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.createAlbum,
                    request_deserializer=musicService__pb2.CreateAlbumRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'updateAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.updateAlbum,
                    request_deserializer=musicService__pb2.UpdateAlbumRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'deleteAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAlbum,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'filterAllGenres': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllGenres,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'getGenreById': grpc.unary_unary_rpc_method_handler(
                    servicer.getGenreById,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'filterGenresByName': grpc.unary_stream_rpc_method_handler(
                    servicer.filterGenresByName,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'createGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.createGenre,
                    request_deserializer=musicService__pb2.CreateGenreRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'updateGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.updateGenre,
                    request_deserializer=musicService__pb2.UpdateGenreRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'deleteGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteGenre,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'filterAllAlbumSongs': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllAlbumSongs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'getAlbumSongByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.getAlbumSongByIds,
                    request_deserializer=musicService__pb2.CreateAlbumSongRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'filterAlbumSongsByAlbumId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAlbumSongsByAlbumId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'filterAlbumSongsBySongId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAlbumSongsBySongId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'createAlbumSong': grpc.unary_unary_rpc_method_handler(
                    servicer.createAlbumSong,
                    request_deserializer=musicService__pb2.CreateAlbumSongRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'deleteAlbumSong': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteAlbumSong,
                    request_deserializer=musicService__pb2.CreateAlbumSongRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'filterAllGenreSongs': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllGenreSongs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'getGenreSongByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.getGenreSongByIds,
                    request_deserializer=musicService__pb2.CreateGenreSongRequest.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'filterGenreSongsByGenreId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterGenreSongsByGenreId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'filterGenreSongsBySongId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterGenreSongsBySongId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'createGenreSong': grpc.unary_unary_rpc_method_handler(
                    servicer.createGenreSong,
                    request_deserializer=musicService__pb2.CreateGenreSongRequest.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'deleteGenreSong': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteGenreSong,
                    request_deserializer=musicService__pb2.CreateGenreSongRequest.FromString,
                    response_serializer=musicService__pb2.GenreSong.SerializeToString,
            ),
            'filterAllSongSubArtists': grpc.unary_stream_rpc_method_handler(
                    servicer.filterAllSongSubArtists,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
            'getSongSubArtistByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.getSongSubArtistByIds,
                    request_deserializer=musicService__pb2.CreateSongSubArtistRequest.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
            'filterSongSubArtistsBySongId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterSongSubArtistsBySongId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
            'filterSongSubArtistsBySubArtistId': grpc.unary_stream_rpc_method_handler(
                    servicer.filterSongSubArtistsBySubArtistId,
                    request_deserializer=musicService__pb2.StringRequest.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
            'createSongSubArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.createSongSubArtist,
                    request_deserializer=musicService__pb2.CreateSongSubArtistRequest.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
            'deleteSongSubArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteSongSubArtist,
                    request_deserializer=musicService__pb2.CreateSongSubArtistRequest.FromString,
                    response_serializer=musicService__pb2.SongSubArtist.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def filterAllSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllSongs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSongById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getSongById',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterSongsByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterSongsByTitle',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterSongsByArtistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterSongsByArtistId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterSongsBySongType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterSongsBySongType',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createSong',
            musicService__pb2.CreateSongRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/updateSong',
            musicService__pb2.UpdateSongRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteSong',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAllAlbums(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllAlbums',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAlbumById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getAlbumById',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAlbumsByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAlbumsByName',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAlbumsByArtistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAlbumsByArtistId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createAlbum',
            musicService__pb2.CreateAlbumRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/updateAlbum',
            musicService__pb2.UpdateAlbumRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteAlbum',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAllGenres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllGenres',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getGenreById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getGenreById',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterGenresByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterGenresByName',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createGenre',
            musicService__pb2.CreateGenreRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/updateGenre',
            musicService__pb2.UpdateGenreRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteGenre',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAllAlbumSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllAlbumSongs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAlbumSongByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getAlbumSongByIds',
            musicService__pb2.CreateAlbumSongRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAlbumSongsByAlbumId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAlbumSongsByAlbumId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAlbumSongsBySongId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAlbumSongsBySongId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createAlbumSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createAlbumSong',
            musicService__pb2.CreateAlbumSongRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteAlbumSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteAlbumSong',
            musicService__pb2.CreateAlbumSongRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAllGenreSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllGenreSongs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getGenreSongByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getGenreSongByIds',
            musicService__pb2.CreateGenreSongRequest.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterGenreSongsByGenreId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterGenreSongsByGenreId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterGenreSongsBySongId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterGenreSongsBySongId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createGenreSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createGenreSong',
            musicService__pb2.CreateGenreSongRequest.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteGenreSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteGenreSong',
            musicService__pb2.CreateGenreSongRequest.SerializeToString,
            musicService__pb2.GenreSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterAllSongSubArtists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterAllSongSubArtists',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSongSubArtistByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/getSongSubArtistByIds',
            musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterSongSubArtistsBySongId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterSongSubArtistsBySongId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def filterSongSubArtistsBySubArtistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.music.MusicService/filterSongSubArtistsBySubArtistId',
            musicService__pb2.StringRequest.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createSongSubArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/createSongSubArtist',
            musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteSongSubArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/deleteSongSubArtist',
            musicService__pb2.CreateSongSubArtistRequest.SerializeToString,
            musicService__pb2.SongSubArtist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
