syntax = "proto3";

package app.grpc.protos.storage;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service StorageService {
    rpc uploadToS3(UploadToS3Request) returns (UploadToS3Response) {}
    rpc findById(StringRequest) returns (StorageData) {}
    rpc findAll(google.protobuf.Empty) returns (stream StorageData) {}
    rpc findByIds(ListStringRequest) returns (stream StorageData) {}
    rpc findByFileType(StringRequest) returns (stream StorageData) {}
    rpc findByUserId(StringRequest) returns (stream StorageData) {}
    rpc findByFileName(StringRequest) returns (stream StorageData) {}
    rpc doCreate(CreateRequest) returns (StorageData) {}
    rpc doUpdate(UpdateRequest) returns (StorageData) {}
    rpc doDelete(StringRequest) returns (StorageData) {}
    rpc genPublicUrl(GenPublicUrlRequest) returns (GenPublicUrlResponse) {}
}


message StorageData {
    string id = 1;
    string userId = 2;
    string fileName = 3;
    string fileType = 4;
    string fileSize = 5;
    string fileUrl = 6;
    string description = 7;
    google.protobuf.Timestamp createdAt = 8;
    google.protobuf.Timestamp updatedAt = 9;
    google.protobuf.Timestamp deletedAt = 10;
    bool isActive = 11;
}

message StringRequest {
    string str = 1;
}

message ListStringRequest {
    repeated string strs = 1;
}

message CreateRequest {
    string userId = 1;
    string fileName = 2;
    string fileType = 3;
    string fileSize = 4;
    string fileUrl = 5;
    string description = 6;
}

message UpdateRequest {
    string id = 1;
    string fileName = 2;
    string fileType = 3;
    string fileSize = 4;
    string fileUrl = 5;
    string description = 6;
}

message UploadToS3Request {
    bytes file = 1;
    string fileName = 2;
    string fileType = 3;
}

message UploadToS3Response {
    string key = 1;
    string url = 2;
}

message GenPublicUrlRequest {
    string s3Key = 1;
}

message GenPublicUrlResponse {
    string publicUrl = 1;
}
