version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro
      - ./serverclontify.sql:/serverclontify.sql
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - clontify-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clontify.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - clontify-network

  auth:
    build:
      context: ./appServices/auth
      dockerfile: Dockerfile
    container_name: auth_service
    restart: no
    volumes:
      - ./appServices/common:/auth_service/common
    env_file:
      - .env
    environment:
      - PYTHONPATH=/auth_service/common
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - clontify-network

  users:
    build:
      context: ./appServices/users
      dockerfile: Dockerfile
    container_name: users_service
    restart: no
    volumes:
      - ./appServices/common:/users_service/common
    env_file:
      - .env
    environment:
      - PYTHONPATH=/users_service/common
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - clontify-network

  music:
    build:
      context: ./appServices/music
      dockerfile: Dockerfile
    container_name: music_service
    restart: no
    volumes:
      - ./appServices/common:/music_service/common
    env_file:
      - .env
    environment:
      - PYTHONPATH=/music_service/common
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - clontify-network

  storage:
    build:
      context: ./appServices/storage
      dockerfile: Dockerfile
    container_name: storage_service
    restart: no
    volumes:
      - ./appServices/common:/storage_service/common
    env_file:
      - .env
    environment:
      - PYTHONPATH=/storage_service/common
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    networks:
      - clontify-network


volumes:
  postgres_data:


networks:
  clontify-network:
    driver: bridge