# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import musicService_pb2 as musicService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in musicService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSongById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetSongById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.GetSongsByTitle = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetSongsByTitle',
                request_serializer=musicService__pb2.NameRequest.SerializeToString,
                response_deserializer=musicService__pb2.SongList.FromString,
                _registered_method=True)
        self.CreateSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreateSong',
                request_serializer=musicService__pb2.Song.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.UpdateSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdateSong',
                request_serializer=musicService__pb2.Song.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.DeleteSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeleteSong',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Song.FromString,
                _registered_method=True)
        self.GetAlbumById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetAlbumById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.GetAlbumsByName = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetAlbumsByName',
                request_serializer=musicService__pb2.NameRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumList.FromString,
                _registered_method=True)
        self.CreateAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreateAlbum',
                request_serializer=musicService__pb2.Album.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.UpdateAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdateAlbum',
                request_serializer=musicService__pb2.Album.SerializeToString,
                response_deserializer=musicService__pb2.Album.FromString,
                _registered_method=True)
        self.DeleteAlbum = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeleteAlbum',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Empty.FromString,
                _registered_method=True)
        self.GetGenreById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetGenreById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.GetGenresByName = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetGenresByName',
                request_serializer=musicService__pb2.NameRequest.SerializeToString,
                response_deserializer=musicService__pb2.GenreList.FromString,
                _registered_method=True)
        self.CreateGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreateGenre',
                request_serializer=musicService__pb2.Genre.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.UpdateGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdateGenre',
                request_serializer=musicService__pb2.Genre.SerializeToString,
                response_deserializer=musicService__pb2.Genre.FromString,
                _registered_method=True)
        self.DeleteGenre = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeleteGenre',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPlaylistById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Playlist.FromString,
                _registered_method=True)
        self.GetPlaylistsByName = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistsByName',
                request_serializer=musicService__pb2.NameRequest.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.GetPlaylistsByOwnerId = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistsByOwnerId',
                request_serializer=musicService__pb2.OwnerIdRequest.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreatePlaylist',
                request_serializer=musicService__pb2.Playlist.SerializeToString,
                response_deserializer=musicService__pb2.Playlist.FromString,
                _registered_method=True)
        self.UpdatePlaylist = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdatePlaylist',
                request_serializer=musicService__pb2.Playlist.SerializeToString,
                response_deserializer=musicService__pb2.Playlist.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeletePlaylist',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Empty.FromString,
                _registered_method=True)
        self.GetAlbumSongById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetAlbumSongById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.GetAlbumSongsByAlbumId = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetAlbumSongsByAlbumId',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSongList.FromString,
                _registered_method=True)
        self.GetAlbumSongsBySongId = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetAlbumSongsBySongId',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSongList.FromString,
                _registered_method=True)
        self.CreateAlbumSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreateAlbumSong',
                request_serializer=musicService__pb2.AlbumSong.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.UpdateAlbumSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdateAlbumSong',
                request_serializer=musicService__pb2.AlbumSong.SerializeToString,
                response_deserializer=musicService__pb2.AlbumSong.FromString,
                _registered_method=True)
        self.DeleteAlbumSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeleteAlbumSong',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPlaylistSongById = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistSongById',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistSong.FromString,
                _registered_method=True)
        self.GetPlaylistSongsByPlaylistId = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistSongsByPlaylistId',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistSongList.FromString,
                _registered_method=True)
        self.GetPlaylistSongsBySongId = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/GetPlaylistSongsBySongId',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistSongList.FromString,
                _registered_method=True)
        self.CreatePlaylistSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/CreatePlaylistSong',
                request_serializer=musicService__pb2.PlaylistSong.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistSong.FromString,
                _registered_method=True)
        self.UpdatePlaylistSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/UpdatePlaylistSong',
                request_serializer=musicService__pb2.PlaylistSong.SerializeToString,
                response_deserializer=musicService__pb2.PlaylistSong.FromString,
                _registered_method=True)
        self.DeletePlaylistSong = channel.unary_unary(
                '/app.grpc.protos.music.MusicService/DeletePlaylistSong',
                request_serializer=musicService__pb2.IdRequest.SerializeToString,
                response_deserializer=musicService__pb2.Empty.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSongById(self, request, context):
        """Song
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSongsByTitle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumById(self, request, context):
        """Album
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumsByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenreById(self, request, context):
        """Genre
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenresByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistById(self, request, context):
        """Playlist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsByOwnerId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumSongById(self, request, context):
        """AlbumSong
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumSongsByAlbumId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumSongsBySongId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAlbumSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAlbumSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlbumSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistSongById(self, request, context):
        """PlaylistSong
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistSongsByPlaylistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistSongsBySongId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylistSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlaylistSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylistSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSongById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'GetSongsByTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSongsByTitle,
                    request_deserializer=musicService__pb2.NameRequest.FromString,
                    response_serializer=musicService__pb2.SongList.SerializeToString,
            ),
            'CreateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSong,
                    request_deserializer=musicService__pb2.Song.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'UpdateSong': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSong,
                    request_deserializer=musicService__pb2.Song.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'DeleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSong,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Song.SerializeToString,
            ),
            'GetAlbumById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'GetAlbumsByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumsByName,
                    request_deserializer=musicService__pb2.NameRequest.FromString,
                    response_serializer=musicService__pb2.AlbumList.SerializeToString,
            ),
            'CreateAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlbum,
                    request_deserializer=musicService__pb2.Album.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'UpdateAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlbum,
                    request_deserializer=musicService__pb2.Album.FromString,
                    response_serializer=musicService__pb2.Album.SerializeToString,
            ),
            'DeleteAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlbum,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Empty.SerializeToString,
            ),
            'GetGenreById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenreById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'GetGenresByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenresByName,
                    request_deserializer=musicService__pb2.NameRequest.FromString,
                    response_serializer=musicService__pb2.GenreList.SerializeToString,
            ),
            'CreateGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGenre,
                    request_deserializer=musicService__pb2.Genre.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'UpdateGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGenre,
                    request_deserializer=musicService__pb2.Genre.FromString,
                    response_serializer=musicService__pb2.Genre.SerializeToString,
            ),
            'DeleteGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGenre,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Empty.SerializeToString,
            ),
            'GetPlaylistById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Playlist.SerializeToString,
            ),
            'GetPlaylistsByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsByName,
                    request_deserializer=musicService__pb2.NameRequest.FromString,
                    response_serializer=musicService__pb2.PlaylistList.SerializeToString,
            ),
            'GetPlaylistsByOwnerId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsByOwnerId,
                    request_deserializer=musicService__pb2.OwnerIdRequest.FromString,
                    response_serializer=musicService__pb2.PlaylistList.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=musicService__pb2.Playlist.FromString,
                    response_serializer=musicService__pb2.Playlist.SerializeToString,
            ),
            'UpdatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylist,
                    request_deserializer=musicService__pb2.Playlist.FromString,
                    response_serializer=musicService__pb2.Playlist.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Empty.SerializeToString,
            ),
            'GetAlbumSongById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumSongById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'GetAlbumSongsByAlbumId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumSongsByAlbumId,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSongList.SerializeToString,
            ),
            'GetAlbumSongsBySongId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumSongsBySongId,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.AlbumSongList.SerializeToString,
            ),
            'CreateAlbumSong': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlbumSong,
                    request_deserializer=musicService__pb2.AlbumSong.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'UpdateAlbumSong': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAlbumSong,
                    request_deserializer=musicService__pb2.AlbumSong.FromString,
                    response_serializer=musicService__pb2.AlbumSong.SerializeToString,
            ),
            'DeleteAlbumSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlbumSong,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Empty.SerializeToString,
            ),
            'GetPlaylistSongById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistSongById,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.PlaylistSong.SerializeToString,
            ),
            'GetPlaylistSongsByPlaylistId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistSongsByPlaylistId,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.PlaylistSongList.SerializeToString,
            ),
            'GetPlaylistSongsBySongId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistSongsBySongId,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.PlaylistSongList.SerializeToString,
            ),
            'CreatePlaylistSong': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylistSong,
                    request_deserializer=musicService__pb2.PlaylistSong.FromString,
                    response_serializer=musicService__pb2.PlaylistSong.SerializeToString,
            ),
            'UpdatePlaylistSong': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlaylistSong,
                    request_deserializer=musicService__pb2.PlaylistSong.FromString,
                    response_serializer=musicService__pb2.PlaylistSong.SerializeToString,
            ),
            'DeletePlaylistSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylistSong,
                    request_deserializer=musicService__pb2.IdRequest.FromString,
                    response_serializer=musicService__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSongById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetSongById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSongsByTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetSongsByTitle',
            musicService__pb2.NameRequest.SerializeToString,
            musicService__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreateSong',
            musicService__pb2.Song.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdateSong',
            musicService__pb2.Song.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeleteSong',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Song.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetAlbumById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumsByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetAlbumsByName',
            musicService__pb2.NameRequest.SerializeToString,
            musicService__pb2.AlbumList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreateAlbum',
            musicService__pb2.Album.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdateAlbum',
            musicService__pb2.Album.SerializeToString,
            musicService__pb2.Album.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeleteAlbum',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenreById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetGenreById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenresByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetGenresByName',
            musicService__pb2.NameRequest.SerializeToString,
            musicService__pb2.GenreList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreateGenre',
            musicService__pb2.Genre.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdateGenre',
            musicService__pb2.Genre.SerializeToString,
            musicService__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeleteGenre',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistsByName',
            musicService__pb2.NameRequest.SerializeToString,
            musicService__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsByOwnerId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistsByOwnerId',
            musicService__pb2.OwnerIdRequest.SerializeToString,
            musicService__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreatePlaylist',
            musicService__pb2.Playlist.SerializeToString,
            musicService__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdatePlaylist',
            musicService__pb2.Playlist.SerializeToString,
            musicService__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeletePlaylist',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumSongById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetAlbumSongById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumSongsByAlbumId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetAlbumSongsByAlbumId',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.AlbumSongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumSongsBySongId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetAlbumSongsBySongId',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.AlbumSongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAlbumSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreateAlbumSong',
            musicService__pb2.AlbumSong.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAlbumSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdateAlbumSong',
            musicService__pb2.AlbumSong.SerializeToString,
            musicService__pb2.AlbumSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlbumSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeleteAlbumSong',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistSongById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistSongById',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.PlaylistSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistSongsByPlaylistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistSongsByPlaylistId',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.PlaylistSongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistSongsBySongId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/GetPlaylistSongsBySongId',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.PlaylistSongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylistSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/CreatePlaylistSong',
            musicService__pb2.PlaylistSong.SerializeToString,
            musicService__pb2.PlaylistSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlaylistSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/UpdatePlaylistSong',
            musicService__pb2.PlaylistSong.SerializeToString,
            musicService__pb2.PlaylistSong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylistSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.music.MusicService/DeletePlaylistSong',
            musicService__pb2.IdRequest.SerializeToString,
            musicService__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
