# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import storageService_pb2 as storageService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storageService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.uploadToS3 = channel.unary_unary(
                '/app.grpc.protos.storage.StorageService/uploadToS3',
                request_serializer=storageService__pb2.UploadToS3Request.SerializeToString,
                response_deserializer=storageService__pb2.UploadToS3Response.FromString,
                _registered_method=True)
        self.findById = channel.unary_unary(
                '/app.grpc.protos.storage.StorageService/findById',
                request_serializer=storageService__pb2.StringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.findAll = channel.unary_stream(
                '/app.grpc.protos.storage.StorageService/findAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.findByIds = channel.unary_stream(
                '/app.grpc.protos.storage.StorageService/findByIds',
                request_serializer=storageService__pb2.ListStringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.findByFileType = channel.unary_stream(
                '/app.grpc.protos.storage.StorageService/findByFileType',
                request_serializer=storageService__pb2.StringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.findByUserId = channel.unary_stream(
                '/app.grpc.protos.storage.StorageService/findByUserId',
                request_serializer=storageService__pb2.StringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.findByFileName = channel.unary_stream(
                '/app.grpc.protos.storage.StorageService/findByFileName',
                request_serializer=storageService__pb2.StringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.doCreate = channel.unary_unary(
                '/app.grpc.protos.storage.StorageService/doCreate',
                request_serializer=storageService__pb2.CreateRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.doUpdate = channel.unary_unary(
                '/app.grpc.protos.storage.StorageService/doUpdate',
                request_serializer=storageService__pb2.UpdateRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)
        self.doDelete = channel.unary_unary(
                '/app.grpc.protos.storage.StorageService/doDelete',
                request_serializer=storageService__pb2.StringRequest.SerializeToString,
                response_deserializer=storageService__pb2.StorageData.FromString,
                _registered_method=True)


class StorageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def uploadToS3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByFileType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByFileName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'uploadToS3': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadToS3,
                    request_deserializer=storageService__pb2.UploadToS3Request.FromString,
                    response_serializer=storageService__pb2.UploadToS3Response.SerializeToString,
            ),
            'findById': grpc.unary_unary_rpc_method_handler(
                    servicer.findById,
                    request_deserializer=storageService__pb2.StringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'findAll': grpc.unary_stream_rpc_method_handler(
                    servicer.findAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'findByIds': grpc.unary_stream_rpc_method_handler(
                    servicer.findByIds,
                    request_deserializer=storageService__pb2.ListStringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'findByFileType': grpc.unary_stream_rpc_method_handler(
                    servicer.findByFileType,
                    request_deserializer=storageService__pb2.StringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'findByUserId': grpc.unary_stream_rpc_method_handler(
                    servicer.findByUserId,
                    request_deserializer=storageService__pb2.StringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'findByFileName': grpc.unary_stream_rpc_method_handler(
                    servicer.findByFileName,
                    request_deserializer=storageService__pb2.StringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'doCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.doCreate,
                    request_deserializer=storageService__pb2.CreateRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'doUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.doUpdate,
                    request_deserializer=storageService__pb2.UpdateRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
            'doDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.doDelete,
                    request_deserializer=storageService__pb2.StringRequest.FromString,
                    response_serializer=storageService__pb2.StorageData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.storage.StorageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.storage.StorageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def uploadToS3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/uploadToS3',
            storageService__pb2.UploadToS3Request.SerializeToString,
            storageService__pb2.UploadToS3Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findById',
            storageService__pb2.StringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findByIds',
            storageService__pb2.ListStringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByFileType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findByFileType',
            storageService__pb2.StringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findByUserId',
            storageService__pb2.StringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByFileName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/findByFileName',
            storageService__pb2.StringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/doCreate',
            storageService__pb2.CreateRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/doUpdate',
            storageService__pb2.UpdateRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.storage.StorageService/doDelete',
            storageService__pb2.StringRequest.SerializeToString,
            storageService__pb2.StorageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
