syntax = "proto3";

package app.grpc.protos;

service UserService {
    rpc GetProfileByID(GetProfileByIDRequest) returns (GetProfileResponse) {}
    rpc CreateProfile(CreateProfileRequest) returns (CreateProfileResponse) {}
    rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse) {}
    rpc DeleteProfile(DeleteProfileRequest) returns (DeleteProfileResponse) {}
    rpc GetProfileByAccountID(GetProfileByAccountIDRequest) returns (GetProfileByAccountIDResponse) {}
} 

message Profile {
    string id = 1;
    string accountID = 2;
    string fullName = 3;
    string avatarUrl = 4;
    string bio = 5;
    string dateOfBirth = 6;
    string phoneNumber = 7;
    string createdAt = 8;
    string updatedAt = 9;
    string deletedAt = 10;
    bool isActive = 11;
}

message GetProfileByIDRequest {
    string id = 1;
}

message GetProfileResponse {
    Profile profile = 1;
}

message CreateProfileRequest {
    string accountID = 1;
    string fullName = 2;
    string avatarUrl = 3;
    string bio = 4;
    string dateOfBirth = 5;
    string phoneNumber = 6;
}

message CreateProfileResponse {
    Profile profile = 1;
}

message UpdateProfileRequest {
    string id = 1;
    string fullName = 2;
    string avatarUrl = 3;
    string bio = 4;
    string dateOfBirth = 5;
    string phoneNumber = 6;
}

message UpdateProfileResponse {
    Profile profile = 1;
}

message DeleteProfileRequest {
    string id = 1;
}

message DeleteProfileResponse {
    bool success = 1;
}

message GetProfileByAccountIDRequest {
    string accountID = 1;
}

message GetProfileByAccountIDResponse {
    Profile profile = 1;
}