# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import authService_pb2 as authService__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in authService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.findByID = channel.unary_unary(
                '/app.grpc.protos.AuthService/findByID',
                request_serializer=authService__pb2.findByIDRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)
        self.findByUsername = channel.unary_unary(
                '/app.grpc.protos.AuthService/findByUsername',
                request_serializer=authService__pb2.findByUsernameRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)
        self.findByEmail = channel.unary_unary(
                '/app.grpc.protos.AuthService/findByEmail',
                request_serializer=authService__pb2.findByEmailRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)
        self.findByStatus = channel.unary_unary(
                '/app.grpc.protos.AuthService/findByStatus',
                request_serializer=authService__pb2.findByStatusRequest.SerializeToString,
                response_deserializer=authService__pb2.accountListResponse.FromString,
                _registered_method=True)
        self.findByDateCreated = channel.unary_unary(
                '/app.grpc.protos.AuthService/findByDateCreated',
                request_serializer=authService__pb2.findByDateCreatedRequest.SerializeToString,
                response_deserializer=authService__pb2.accountListResponse.FromString,
                _registered_method=True)
        self.doCreate = channel.unary_unary(
                '/app.grpc.protos.AuthService/doCreate',
                request_serializer=authService__pb2.createAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)
        self.doUpdate = channel.unary_unary(
                '/app.grpc.protos.AuthService/doUpdate',
                request_serializer=authService__pb2.updateAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)
        self.doDelete = channel.unary_unary(
                '/app.grpc.protos.AuthService/doDelete',
                request_serializer=authService__pb2.deleteAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.accountResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def findByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByDateCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'findByID': grpc.unary_unary_rpc_method_handler(
                    servicer.findByID,
                    request_deserializer=authService__pb2.findByIDRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
            'findByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.findByUsername,
                    request_deserializer=authService__pb2.findByUsernameRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
            'findByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.findByEmail,
                    request_deserializer=authService__pb2.findByEmailRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
            'findByStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.findByStatus,
                    request_deserializer=authService__pb2.findByStatusRequest.FromString,
                    response_serializer=authService__pb2.accountListResponse.SerializeToString,
            ),
            'findByDateCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.findByDateCreated,
                    request_deserializer=authService__pb2.findByDateCreatedRequest.FromString,
                    response_serializer=authService__pb2.accountListResponse.SerializeToString,
            ),
            'doCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.doCreate,
                    request_deserializer=authService__pb2.createAccountRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
            'doUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.doUpdate,
                    request_deserializer=authService__pb2.updateAccountRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
            'doDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.doDelete,
                    request_deserializer=authService__pb2.deleteAccountRequest.FromString,
                    response_serializer=authService__pb2.accountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def findByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/findByID',
            authService__pb2.findByIDRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/findByUsername',
            authService__pb2.findByUsernameRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/findByEmail',
            authService__pb2.findByEmailRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/findByStatus',
            authService__pb2.findByStatusRequest.SerializeToString,
            authService__pb2.accountListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByDateCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/findByDateCreated',
            authService__pb2.findByDateCreatedRequest.SerializeToString,
            authService__pb2.accountListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/doCreate',
            authService__pb2.createAccountRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/doUpdate',
            authService__pb2.updateAccountRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/doDelete',
            authService__pb2.deleteAccountRequest.SerializeToString,
            authService__pb2.accountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
