# Generated by Django 5.2.1 on 2025-05-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('albumId', 'songId')},
        ),
        migrations.AlterUniqueTogether(
            name='genresong',
            unique_together={('songID', 'genreID')},
        ),
        migrations.AlterUniqueTogether(
            name='songsubartist',
            unique_together={('songID', 'subArtistID')},
        ),
    ]
