# Generated by Django 5.2.1 on 2025-05-11 09:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accountID', models.UUIDField(unique=True)),
                ('fullName', models.TextField(default='noname', max_length=150)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
