class ErrorCodes:
    INVALID_INPUT = 400          # Bad Request
    UNAUTHORIZED = 401           # Unauthorized
    PAYMENT_REQUIRED = 402       # Payment Required
    FORBIDDEN = 403              # Forbidden
    NOT_FOUND = 404              # Not Found
    METHOD_NOT_ALLOWED = 405     # Method Not Allowed
    NOT_ACCEPTABLE = 406         # Not Acceptable
    REQUEST_TIMEOUT = 408        # Request Timeout
    CONFLICT = 409               # Conflict
    ALREADY_EXISTS = 409         # Alias for CONFLICT
    UNSUPPORTED_MEDIA = 415      # Unsupported Media Type
    RANGE_NOT_SATISFIABLE = 416  # Range Not Satisfiable
    TOO_MANY_REQUESTS = 429      # Too Many Requests
    OPERATION_FAILED = 500       # Internal Server Error
    NOT_IMPLEMENTED = 501        # Not Implemented
    BAD_GATEWAY = 502            # Bad Gateway
    SERVICE_UNAVAILABLE = 503    # Service Unavailable
    GATEWAY_TIMEOUT = 504        # Gateway Timeout
    CREATE_FAILED = 550          # creation failure
    UPDATE_FAILED = 551          # update failure
    DELETE_FAILED = 552          # deletion failure
    QUERY_FAILED = 553           # query failure
    INVALID_STATUS = 600         # invalid status
    VALIDATION_ERROR = 601       # validation error
    INVALID_FORMAT = 602         # invalid format
    INVALID_PARAMETER = 603      # invalid parameter
    TOKEN_EXPIRED = 700          # expired token
    INVALID_TOKEN = 701          # invalid token
    INSUFFICIENT_PERMISSIONS = 702  # insufficient permissions
    ACCOUNT_LOCKED = 802          # locked account
    LIMIT_EXCEEDED = 803          # exceeded limits