syntax = "proto3";

package app.grpc.protos;

import "google/protobuf/timestamp.proto";

service AuthService {
  rpc GetAccountByID(GetAccountByIDRequest) returns (AccountResponse) {}
  rpc GetAccountByUsername(GetAccountByUsernameRequest) returns (AccountResponse) {}
  rpc GetAccountByEmail(GetAccountByEmailRequest) returns (AccountResponse) {}
  rpc GetAccountsByStatus(GetAccountsByStatusRequest) returns (AccountListResponse) {}
  rpc GetAccountsByDateCreated(GetAccountsByDateCreatedRequest) returns (AccountListResponse) {}
  rpc CreateAccount(CreateAccountRequest) returns (AccountResponse) {}
  rpc UpdateAccount(UpdateAccountRequest) returns (AccountResponse) {}
  rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse) {}

  rpc Login(LoginRequest) returns (LoginResponse) {}
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {}
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse) {}
}

message PaginationParams {
  int32 page = 1;
  int32 pageSize = 2;
}

message GetAccountByIDRequest {
  string id = 1;
}

message GetAccountByUsernameRequest {
  string username = 1;
}

message GetAccountByEmailRequest {
  string email = 1;
}

message GetAccountsByStatusRequest {
  bool isActive = 1;
  PaginationParams pagination = 2;
}

message GetAccountsByDateCreatedRequest {
  google.protobuf.Timestamp start = 1;
  google.protobuf.Timestamp end = 2;
  PaginationParams pagination = 3;
}

message CreateAccountRequest {
  string roleId = 1;
  string username = 2;
  string email = 3;
  string password = 4;
}

message UpdateAccountRequest {
  string id = 1;
  string roleId = 2;
  string email = 3;
  string password = 4;
  bool isActive = 5;
}

message DeleteAccountRequest {
  string id = 1;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message RefreshTokenRequest {
  string refreshToken = 1;
}

message ValidateTokenRequest {
  string accessToken = 1;
}

message AccountResponse {
  string id = 1;
  string roleId = 2;
  string username = 3;
  string email = 4;
  bool isActive = 5;
  google.protobuf.Timestamp createdAt = 6;
  google.protobuf.Timestamp updatedAt = 7;
  google.protobuf.Timestamp deletedAt = 8;
}

message AccountListResponse {
  int32 totalCount = 1;
  int32 page = 2;
  int32 pageSize = 3;
  repeated AccountResponse accounts = 4;
}

message DeleteAccountResponse {
  bool success = 1;
  string message = 2;
}

message LoginResponse {
  string accessToken = 1;
  string refreshToken = 2;
  google.protobuf.Timestamp expiresAt = 3;
  AccountResponse account = 4;
}

message RefreshTokenResponse {
  string accessToken = 1;
  string refreshToken = 2;
  google.protobuf.Timestamp expiresAt = 3;
}

message ValidateTokenResponse {
  bool isValid = 1;
  AccountResponse account = 2;
}

message ErrorResponse {
  string code = 1;
  string message = 2;
  repeated string details = 3;
}
