"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z#k11jjcc0&6l^a$601$1y8onv70k)1d1z+1^nauk32qrkoevn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "app",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "common.jwtMiddleware.JwtMiddleware",
    "common.roleMiddleware.RoleMiddleware"
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "usersservice",
        "USER": "admin",
        "PASSWORD": "admin",
        "HOST": "postgres",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

PUBLIC_ENDPOINTS = [

]
ACCESSIBILITY = {
    'ADMIN_REQUIRED': [

    ],
    'ARTIST_REQUIRED': [

    ],
    'USER_REQUIRED': [

    ]
}
ROOT_URLCONF = "config.urls"

CORS_ALLOWED_ORIGINS = [
    "https://fe-spotify.vercel.app",
    "http://localhost:50050",
    "http://localhost:8080",
    "http://localhost:50052",
    "http://localhost:8082",
    "http://localhost:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "https://fe-spotify.vercel.app",
    "http://localhost:50050",
    "http://localhost:8080",
    "http://localhost:50052",
    "http://localhost:8082",
    "http://localhost:5173",
]

def parseBoolean(value):
    return str(value).lower() in ('true', '1', 't', 'yes', 'y')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME", 30))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME", 7))),
    'ROTATE_REFRESH_TOKENS': parseBoolean(os.environ.get("JWT_ROTATE_REFRESH_TOKENS", "True")),
    'BLACKLIST_AFTER_ROTATION': parseBoolean(os.environ.get("JWT_BLACKLIST_AFTER_ROTATION", "True")),
    'ALGORITHM': os.environ.get("JWT_ALGORITHM", ""),
    'SIGNING_KEY': os.environ.get("JWT_SECRET_KEY", ""),
    'VERIFYING_KEY': os.environ.get("JWT_VERIFYING_KEY", None),
    'AUTH_HEADER_TYPES': os.environ.get("JWT_AUTH_HEADER_TYPES", ("Bearer",)),
    'AUTH_TOKEN_CLASSES': os.environ.get("JWT_AUTH_TOKEN_CLASSES", ("rest_framework_simplejwt.tokens.AccessToken",)),
    'USER_ID_FIELD': os.environ.get("JWT_USER_ID_FIELD", "id"),
    'USER_ID_CLAIM': os.environ.get("JWT_USER_ID_CLAIM", "user_id"),
}

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

CORS_ALLOW_CREDENTIALS = parseBoolean(os.environ.get("CORS_ALLOW_CREDENTIALS", "True"))
CSRF_COOKIE_HTTPONLY = parseBoolean(os.environ.get("CSRF_COOKIE_HTTPONLY", "False"))
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = parseBoolean(os.environ.get("CSRF_COOKIE_SECURE", "False"))
CSRF_COOKIE_AGE = int(os.environ.get("CSRF_COOKIE_AGE", "604800"))

AUTH_GRPC_HOST = os.environ.get("AUTH_GRPC_HOST", "auth_service")
AUTH_GRPC_PORT = os.environ.get("AUTH_GRPC_PORT", "50050")