# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import authService_pb2 as authService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in authService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccountByID = channel.unary_unary(
                '/app.grpc.protos.AuthService/GetAccountByID',
                request_serializer=authService__pb2.GetAccountByIDRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetAccountByUsername = channel.unary_unary(
                '/app.grpc.protos.AuthService/GetAccountByUsername',
                request_serializer=authService__pb2.GetAccountByUsernameRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetAccountByEmail = channel.unary_unary(
                '/app.grpc.protos.AuthService/GetAccountByEmail',
                request_serializer=authService__pb2.GetAccountByEmailRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.GetAccountsByStatus = channel.unary_unary(
                '/app.grpc.protos.AuthService/GetAccountsByStatus',
                request_serializer=authService__pb2.GetAccountsByStatusRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountListResponse.FromString,
                _registered_method=True)
        self.GetAccountsByDateCreated = channel.unary_unary(
                '/app.grpc.protos.AuthService/GetAccountsByDateCreated',
                request_serializer=authService__pb2.GetAccountsByDateCreatedRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountListResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/app.grpc.protos.AuthService/CreateAccount',
                request_serializer=authService__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.UpdateAccount = channel.unary_unary(
                '/app.grpc.protos.AuthService/UpdateAccount',
                request_serializer=authService__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.DeleteAccount = channel.unary_unary(
                '/app.grpc.protos.AuthService/DeleteAccount',
                request_serializer=authService__pb2.DeleteAccountRequest.SerializeToString,
                response_deserializer=authService__pb2.DeleteAccountResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/app.grpc.protos.AuthService/Login',
                request_serializer=authService__pb2.LoginRequest.SerializeToString,
                response_deserializer=authService__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/app.grpc.protos.AuthService/RefreshToken',
                request_serializer=authService__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=authService__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/app.grpc.protos.AuthService/ValidateToken',
                request_serializer=authService__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=authService__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAccountByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsByStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountsByDateCreated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccountByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByID,
                    request_deserializer=authService__pb2.GetAccountByIDRequest.FromString,
                    response_serializer=authService__pb2.AccountResponse.SerializeToString,
            ),
            'GetAccountByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByUsername,
                    request_deserializer=authService__pb2.GetAccountByUsernameRequest.FromString,
                    response_serializer=authService__pb2.AccountResponse.SerializeToString,
            ),
            'GetAccountByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountByEmail,
                    request_deserializer=authService__pb2.GetAccountByEmailRequest.FromString,
                    response_serializer=authService__pb2.AccountResponse.SerializeToString,
            ),
            'GetAccountsByStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountsByStatus,
                    request_deserializer=authService__pb2.GetAccountsByStatusRequest.FromString,
                    response_serializer=authService__pb2.AccountListResponse.SerializeToString,
            ),
            'GetAccountsByDateCreated': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountsByDateCreated,
                    request_deserializer=authService__pb2.GetAccountsByDateCreatedRequest.FromString,
                    response_serializer=authService__pb2.AccountListResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=authService__pb2.CreateAccountRequest.FromString,
                    response_serializer=authService__pb2.AccountResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=authService__pb2.UpdateAccountRequest.FromString,
                    response_serializer=authService__pb2.AccountResponse.SerializeToString,
            ),
            'DeleteAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccount,
                    request_deserializer=authService__pb2.DeleteAccountRequest.FromString,
                    response_serializer=authService__pb2.DeleteAccountResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=authService__pb2.LoginRequest.FromString,
                    response_serializer=authService__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=authService__pb2.RefreshTokenRequest.FromString,
                    response_serializer=authService__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=authService__pb2.ValidateTokenRequest.FromString,
                    response_serializer=authService__pb2.ValidateTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAccountByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/GetAccountByID',
            authService__pb2.GetAccountByIDRequest.SerializeToString,
            authService__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/GetAccountByUsername',
            authService__pb2.GetAccountByUsernameRequest.SerializeToString,
            authService__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/GetAccountByEmail',
            authService__pb2.GetAccountByEmailRequest.SerializeToString,
            authService__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountsByStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/GetAccountsByStatus',
            authService__pb2.GetAccountsByStatusRequest.SerializeToString,
            authService__pb2.AccountListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountsByDateCreated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/GetAccountsByDateCreated',
            authService__pb2.GetAccountsByDateCreatedRequest.SerializeToString,
            authService__pb2.AccountListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/CreateAccount',
            authService__pb2.CreateAccountRequest.SerializeToString,
            authService__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/UpdateAccount',
            authService__pb2.UpdateAccountRequest.SerializeToString,
            authService__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/DeleteAccount',
            authService__pb2.DeleteAccountRequest.SerializeToString,
            authService__pb2.DeleteAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/Login',
            authService__pb2.LoginRequest.SerializeToString,
            authService__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/RefreshToken',
            authService__pb2.RefreshTokenRequest.SerializeToString,
            authService__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.AuthService/ValidateToken',
            authService__pb2.ValidateTokenRequest.SerializeToString,
            authService__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
