syntax = "proto3";

package app.grpc.protos;
import "google/protobuf/timestamp.proto";

service UsersService {
    rpc findByID(GetProfileByIDRequest) returns (ProfileResponse) {}
    rpc doCreate(CreateProfileRequest) returns (ProfileResponse) {}
    rpc doUpdate(UpdateProfileRequest) returns (ProfileResponse) {}
    rpc doDelete(DeleteProfileRequest) returns (ProfileResponse) {}
    rpc findByAccountID(GetProfileByAccountIDRequest) returns (ProfileResponse) {}
} 

message ProfileResponse {
    string id = 1;
    string accountID = 2;
    string fullName = 3;
    string avatarUrl = 4;
    string bio = 5;
    google.protobuf.Timestamp dateOfBirth = 6;
    string phoneNumber = 7;
    google.protobuf.Timestamp createdAt = 8;
    google.protobuf.Timestamp updatedAt = 9;
    google.protobuf.Timestamp deletedAt = 10;
    bool isActive = 11;
}

message GetProfileByIDRequest {
    string id = 1;
}

message CreateProfileRequest {
    string accountID = 1;
    string fullName = 2;
    string avatarUrl = 3;
    string bio = 4;
    google.protobuf.Timestamp dateOfBirth = 5;
    string phoneNumber = 6;
}

message UpdateProfileRequest {
    string id = 1;
    string fullName = 2;
    string avatarUrl = 3;
    string bio = 4;
    google.protobuf.Timestamp dateOfBirth = 5;
    string phoneNumber = 6;
}

message DeleteProfileRequest {
    string id = 1;
}


message GetProfileByAccountIDRequest {
    string accountID = 1;
}