# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import usersService_pb2 as usersService__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usersService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.findByID = channel.unary_unary(
                '/app.grpc.protos.UsersService/findByID',
                request_serializer=usersService__pb2.GetProfileByIDRequest.SerializeToString,
                response_deserializer=usersService__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.doCreate = channel.unary_unary(
                '/app.grpc.protos.UsersService/doCreate',
                request_serializer=usersService__pb2.CreateProfileRequest.SerializeToString,
                response_deserializer=usersService__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.doUpdate = channel.unary_unary(
                '/app.grpc.protos.UsersService/doUpdate',
                request_serializer=usersService__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=usersService__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.doDelete = channel.unary_unary(
                '/app.grpc.protos.UsersService/doDelete',
                request_serializer=usersService__pb2.DeleteProfileRequest.SerializeToString,
                response_deserializer=usersService__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.findByAccountID = channel.unary_unary(
                '/app.grpc.protos.UsersService/findByAccountID',
                request_serializer=usersService__pb2.GetProfileByAccountIDRequest.SerializeToString,
                response_deserializer=usersService__pb2.ProfileResponse.FromString,
                _registered_method=True)


class UsersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def findByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findByAccountID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'findByID': grpc.unary_unary_rpc_method_handler(
                    servicer.findByID,
                    request_deserializer=usersService__pb2.GetProfileByIDRequest.FromString,
                    response_serializer=usersService__pb2.ProfileResponse.SerializeToString,
            ),
            'doCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.doCreate,
                    request_deserializer=usersService__pb2.CreateProfileRequest.FromString,
                    response_serializer=usersService__pb2.ProfileResponse.SerializeToString,
            ),
            'doUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.doUpdate,
                    request_deserializer=usersService__pb2.UpdateProfileRequest.FromString,
                    response_serializer=usersService__pb2.ProfileResponse.SerializeToString,
            ),
            'doDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.doDelete,
                    request_deserializer=usersService__pb2.DeleteProfileRequest.FromString,
                    response_serializer=usersService__pb2.ProfileResponse.SerializeToString,
            ),
            'findByAccountID': grpc.unary_unary_rpc_method_handler(
                    servicer.findByAccountID,
                    request_deserializer=usersService__pb2.GetProfileByAccountIDRequest.FromString,
                    response_serializer=usersService__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.protos.UsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('app.grpc.protos.UsersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def findByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.UsersService/findByID',
            usersService__pb2.GetProfileByIDRequest.SerializeToString,
            usersService__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.UsersService/doCreate',
            usersService__pb2.CreateProfileRequest.SerializeToString,
            usersService__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.UsersService/doUpdate',
            usersService__pb2.UpdateProfileRequest.SerializeToString,
            usersService__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.UsersService/doDelete',
            usersService__pb2.DeleteProfileRequest.SerializeToString,
            usersService__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findByAccountID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/app.grpc.protos.UsersService/findByAccountID',
            usersService__pb2.GetProfileByAccountIDRequest.SerializeToString,
            usersService__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
